# Generated by Django 5.0.6 on 2024-06-19 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escolhas',
            new_name='Escolha',
        ),
    ]
